### PR TITLE
add Augsburg as additionalLocation

### PR DESCRIPTION
**Pull request by T0biii**
as suggested here: https://github.com/freifunk/directory.api.freifunk.net/pull/689#issuecomment-1196359595
as we do not have a geCode for this Location i used the HBF

### CODE REVIEW

**Review by krombel — COMMENTED** [review]
Maybe @GoliathLabs has a more fitting address to place there.
For my part at least I think that is right.

I would fix indenting though 😉

**Comment by GoliathLabs** [comment]
We don't have a location yet. The HQ is more or less the same as for FFMUC. Until a suitable location is found, we can use this location.

**Comment by T0biii** [comment]
hey @GoliathLabs the CI(worklow) should repair the structur on his own as seen here: https://github.com/freifunkMUC/freifunk.net-API/commit/b325d5bab25449e2a3805ffcc1555e81fb641b1b

**Comment by GoliathLabs** [comment]
You're right

**Pull request merged**
